version: '3'

services:
  mysql:
    build: 
      context: ./
      dockerfile: ./DB/Dockerfile
    container_name: mysql-container
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  backend:
    build:
      context: ./DS2022_30443_Haragas_Alexandru_Assignment_1_Backend
      dockerfile: ./Dockerfile
    container_name: backend
    restart: always
    ports:
     - "8081:8080"
    environment:
    
       MYSQL_USER: root
       MYSQL_PASSWORD: 1234
       MYSQL_DB_NAME: ds_proj_db
       MYSQL_DATABASE_PORT: 3307
    depends_on:
     - mysql
    links:
     - mysql
  
  frontend:
    build:
      context: ./DS2022_30443_Haragas_Alexandru_Assignment_1_Frontend/frontend
      dockerfile: ./Dockerfile
    container_name: frontend
    restart: always
    ports:
     - "3001:3000"
    environment: 
     - DB_API = http://backend:8081/db-api-1.0.0
    depends_on:
     - backend
    links:
     - backend

volumes:
    database-data: { }